# permissions for end users to edit topologycompositions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topologycomposition-editor-role
rules:
- apiGroups:
  - plumber.ugent.be
  resources:
  - topologycompositions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.ugent.be
  resources:
  - topologycompositions/status
  verbs:
  - get
